### ISSUE TITLE
ArrayIndexOutOfBoundsException at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType

### ISSUE THREAD

**Issue by i23098** [eclipse-jdt/eclipse.jdt#101]
Hi, sorry if this is not the correct place to raise the issue.

I have a multi-project gradle and in one of the sub-projects, if I have to disable the Java Builder or else I just get errors... I removed the .log file, restarted eclipse, got errors like these in the logs [log.txt](https://github.com/eclipse-jdt/eclipse.jdt/files/15261290/log.txt):

```
!ENTRY org.eclipse.jdt.core.manipulation 4 0 2024-05-09 11:46:26.482
!MESSAGE Error in JDT Core during AST creation
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1841)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.initializeUsesNullTypeAnnotation(LookupEnvironment.java:1677)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.usesNullTypeAnnotations(LookupEnvironment.java:1650)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.usesNullTypeAnnotations(LookupEnvironment.java:1645)
        at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.scanFieldForNullAnnotation(BinaryTypeBinding.java:2067)
        at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:652)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1071)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1052)
        at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:316)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:289)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1855)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1824)
        at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitScope.getDefaultImports(GroovyCompilationUnitScope.java:95)
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.checkAndSetImports(CompilationUnitScope.java:275)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment$CompleteTypeBindingsSteps.perform(LookupEnvironment.java:174)
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:552)
        at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:904)
        at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:402)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1286)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:828)
        at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1242)
        at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1120)
        at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5835)
        at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1120)
        at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:868)
        at org.eclipse.jdt.core.manipulation.CoreASTProvider$1.run(CoreASTProvider.java:294)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:286)
        at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
        at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)
        at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:167)
        at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.lambda$0(SelectionListenerWithASTManager.java:149)
        at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5835)
        at org.eclipse.jdt.internal.core.JavaModelManager.callReadOnly(JavaModelManager.java:5824)
        at org.eclipse.jdt.core.JavaCore.callReadOnly(JavaCore.java:6126)
        at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.run(SelectionListenerWithASTManager.java:149)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

Of course, by disabling it, I get another set of issues :(

Can't seem to reproduce on other projects nor understand why this particular project causes an issue (it's one of the simplest in the multi-project)...

**Comment by iloveeclipse** [comment]
`org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitScope.getDefaultImports(GroovyCompilationUnitScope.java:95)`

Please try to uninstall groovy support. The stack trace should be reported to the groovy plugin provider, not here.
