### ISSUE TITLE
"internal error" when running unit tests from the top level.

### ISSUE THREAD

**Issue by stu-at-elexity-io** [eclipse-jdt/eclipse.jdt#114]
I have a medium sized project with a few hundred unit tests classes. I have always ... until now ... been able to run all of the unit tests by right clicking on src/test/java and selecting Run As ... Unit Test. Now that causes an error (see below).

I can still run the unit tests by right-clicking on each package individually and selecting Run As ... Unit Test. I can run them from the command line (using maven, if it's important). It's only from the top level that causes an Eclipse issue.

> An internal error occurred during: "Launching java".

The stack trace is:
`java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.enumerateTypesInPackage(JUnitLaunchConfigurationDelegate.java:543)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.collectExecutionArguments(JUnitLaunchConfigurationDelegate.java:473)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getVMRunnerConfiguration(JUnitLaunchConfigurationDelegate.java:182)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.launch(JUnitLaunchConfigurationDelegate.java:275)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1054)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

The session data is:
`eclipse.buildId=4.33.0.20240905-0613
java.version=21.0.4
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/home/stu/eclipse-workspace/
`
I hope I'm logging this issue in the right place, and thank you for your help!

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1651
