### ISSUE TITLE
Launching test causes ResourceException: Marker id not found

### ISSUE THREAD

**Issue by klaymore142** [eclipse-jdt/eclipse.jdt#18]
We are developing a plugin for Eclipse which launches JUnit tests from LaunchConfigurations, and sometimes see errors with stack traces like:
```
[ERROR] org.eclipse.core.internal.resources.ResourceException: Marker id 26981 not found.
at com.parasoft.xtest.testassist.eclipse.internal.actions.EclipseJUnitLauncher$1.run(EclipseJUnitLauncher.java:167)com.parasoft.xtest.testassist.api.launching.LaunchConfigurationException: org.eclipse.core.internal.resources.ResourceException: Marker id 141280 not found.
        at com.parasoft.xtest.testassist.eclipse.internal.view.launching.EclipseLaunchConfiguration.launch(EclipseLaunchConfiguration.java:55) ~[?:?]
        at com.parasoft.xtest.testassist.eclipse.internal.actions.EclipseJUnitLauncher$1.performLaunch(EclipseJUnitLauncher.java:188) ~[?:?]
        at com.parasoft.xtest.testassist.eclipse.internal.actions.EclipseJUnitLauncher$1.run(EclipseJUnitLauncher.java:156) ~[?:?]
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63) ~[?:?]
Caused by: org.eclipse.core.internal.resources.ResourceException: Marker id 26981 not found.
        at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:83) ~[?:?]
        at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:128) ~[?:?]
        at org.eclipse.debug.core.model.LaunchConfigurationDelegate.isLaunchProblem(LaunchConfigurationDelegate.java:383) ~[?:?]
        at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.isLaunchProblem(AbstractJavaLaunchConfigurationDelegate.java:1004) ~[?:?]
        at org.eclipse.debug.core.model.LaunchConfigurationDelegate.existsProblems(LaunchConfigurationDelegate.java:364) ~[?:?]
        at org.eclipse.debug.core.model.LaunchConfigurationDelegate.finalLaunchCheck(LaunchConfigurationDelegate.java:167) ~[?:?]
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:788) ~[?:?]
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716) ~[?:?]
        at com.parasoft.xtest.testassist.eclipse.internal.view.launching.EclipseLaunchConfiguration.launch(EclipseLaunchConfiguration.java:53) ~[?:?]
```
From what we can tell, there is an invalid Marker which causes the launch to fail. This only happens occasionally, and is difficult to reproduce. It makes sense to me that JDT launching should either clean up invalid markers internally, or ignore markers which are obsolete.

**Comment by jukzi** [comment]
This should be handled in org.eclipse.debug.core.model.LaunchConfigurationDelegate.isLaunchProblem(IMarker)
like https://github.com/eclipse-platform/eclipse.platform.debug/issues/136
see https://github.com/eclipse-platform/eclipse.platform.debug/blob/a5aef833d89bffc9c9af3f4b158864b7779a02dd/org.eclipse.debug.core/core/org/eclipse/debug/core/model/LaunchConfigurationDelegate.java#L389
@klaymore142 do you mind to contribute a PR?

**Comment by jukzi** [comment]
not JDT - reopen at https://github.com/eclipse-platform/eclipse.platform.debug if needed
