### ISSUE TITLE
SWT cocoa NSImage error

### ISSUE THREAD

**Issue by mogilka** [eclipse-jdt/eclipse.jdt#69]
I have found no Eclipse SWT repository so I decide to public my issue here. Please guide me to the right place if I'm wrong.

I have a Java project when I use pure SWT and Jface (no PDE). I work with the project under MacOS and Ubuntu, synchronizing it via Git. I have no error under Linux while running my project. But it occures under MacOS Catalina in 2 places related to TabFolder:

`folder = new TabFolder(grCosmogram, SWT.BORDER);
folder.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true));
Tab[] tabs = initTabs();
for (Tab tab : tabs) {
TabItem item = new TabItem(folder, SWT.CLOSE);
item.setText(tab.name);
item.setControl(tab.control);
}
folder.pack(); //error occures
`

`ToolBar toolbar = dirView.getToolbar(folder, window);
folder.setTopRight(toolbar, SWT.RIGHT);
folder.setSelection(tabcnt); //error occures
`

The TabFolder error:

`java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSImage.size()" because "this.image.handle" is null
	at org.eclipse.swt.widgets.Button.cellSizeForBounds(Button.java:153)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6580)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_stret(Native Method)
	at org.eclipse.swt.internal.cocoa.NSCell.cellSize(NSCell.java:37)
	at org.eclipse.swt.widgets.Button.computeSize(Button.java:224)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:232)
	at org.eclipse.swt.widgets.TabFolder.minimumSize(TabFolder.java:447)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:238)
	at org.eclipse.swt.widgets.TabFolder.computeSize(TabFolder.java:143)
	at org.eclipse.swt.widgets.Control.pack(Control.java:2799)
	at org.eclipse.swt.widgets.Control.pack(Control.java:2773)
`

The CTabFolder error:

`java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSImage.size()" because "this.image.handle" is null
	at org.eclipse.swt.widgets.Button.cellSizeForBounds(Button.java:153)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6580)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_stret(Native Method)
	at org.eclipse.swt.internal.cocoa.NSCell.cellSize(NSCell.java:37)
	at org.eclipse.swt.widgets.Button.computeSize(Button.java:224)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:232)
	at org.eclipse.swt.widgets.TabFolder.minimumSize(TabFolder.java:447)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:238)
	at org.eclipse.swt.widgets.TabFolder.computeSize(TabFolder.java:143)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:232)
	at org.eclipse.swt.custom.SashFormLayout.computeSize(SashFormLayout.java:50)
	at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:232)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:201)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1308)
	at org.eclipse.swt.widgets.Composite.resized(Composite.java:1030)
	at org.eclipse.swt.widgets.Group.resized(Group.java:231)
	at org.eclipse.swt.widgets.Control.setFrameSize(Control.java:3989)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6308)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSView.setFrame(NSView.java:252)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3711)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3752)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3237)
`

How to fix it? I use the latest [Standard Widget Toolkit For Mac OS X (Cocoa) 3.124.0

![Снимок экрана 2023-08-31 в 21 33 36](https://github.com/eclipse-jdt/eclipse.jdt/assets/36766/c8f089f1-8c3f-46c8-bd35-47d1935f5e93)

**Comment by iloveeclipse** [comment]
> Please guide me to the right place if I'm wrong.

https://github.com/eclipse-platform/eclipse.platform.swt/issues
